#!/bin/bash

# extract protein sequences for viruses of interest from compendium alignments
#
# MDS 4.18.2019


outf=all_ppm_data.txt
rm -f $outf

viruses=(hiv siv)
genes=(env gag nef pol rev tat vif vpr vpu)

for virus in ${viruses[@]}
do
   for gene in ${genes[@]}
   do

	   # printf "%d\t%s\t%s\t%s\n" $i $virus $virus_seq_id $gene
      ./create_ppm -p $virus -p $gene HIV1_ALL_2017_${gene}_PRO.fasta.${virus}.fasta >> $outf

   done
done
